name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_install: true
      # Use simple_matrix to limit the number of created jobs
      # phpunit.xml.dist has a large number of testsuites, all of which are tested with
      # multiple versions of php + databases in both the modules themselves and other recipes
      # such as recipe-form-building
      simple_matrix: true
      # Also include jobs with the lowest version of PHP with --prefer-lowest and
      # the highest version of PHP to ensure everything installs
      # Run recipe-cms testsuite because that's the most likely to have weird conflicts e.g. graphql
      extra_jobs: |
        - php: 8.1
          composer_args: --prefer-lowest
          phpunit: true
          phpunit_suite: recipe-cms
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-cms
