name: CI

on:
  push:

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_intall: true
      # Use simple_matrix to limit the number of created jobs
      # phpunit.xml.dist has a large number of testsuites, all of which are tested with
      # multiple versions of php + databases in both the modules themselves and other recipes
      # such as recipe-form-building
      simple_matrix: true
