name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every day at 3:00pm UTC
  schedule:
    - cron: '0 15 * * *'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_install: true
      dynamic_matrix: false
      extra_jobs: |
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-cms
        - php: 8.2
          phpunit: true
          phpunit_suite: framework-orm
        - php: 8.2
          phpunit: true
          phpunit_suite: framework-core
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-cms
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-ccl
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-solr-search
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-authoring-tools
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-blog
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-collaboration
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-content-blocks
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-form-building
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-reporting-tools
        - php: 8.2
          phpunit: true
          phpunit_suite: recipe-services
        - php: 8.2
          phpunit: true
          phpunit_suite: optional-authenticators
        - php: 8.2
          phpunit: true
          phpunit_suite: mfa
