name: Module CI

on:
  push: ~
  # apparently the tilde allows manually running things?
  # https://github.com/Behat/Behat/pull/1361/files
  pull_request: ~

jobs:
  ci:
    uses: emteknetnz/github-actions-ci-cd/.github/workflows/ci.yml@dynamic